### ISSUE TITLE
Find dialog finds itself again

### ISSUE THREAD

**Issue by CaviaPorcellus** [GiovanH/unofficial-homestuck-collection#343]
**Describe the bug**
Searching for text using the find function (ctrl-f) finds not just text on the displayed page, but words in the find dialog box itself (e.g., it finds the word "match" once when it only appears in the dialog)."Of" never gets found in the box though, just "matches" and parts of it, even just one of its letters.

**To Reproduce**
1. Open find function.
2. Type "match".
3. Confusingly note the highlighted "match" within the find dialog box, which is also duplicated for fun.

**Expected behavior**
Find shouldn't find itself.

**Screenshots**
![Screenshot_20220224_225909](https://user-images.githubusercontent.com/5825551/155651537-9ef60947-7038-42f7-8636-2847fae46c41.png)

**Desktop**
 - Program version 2.0.5
 - Asset Pack Version 2
 - OS: Kubuntu 21.10

**Additional context**
This was in theory fixed already in https://github.com/Bambosh/unofficial-homestuck-collection/issues/82#issue-797152992.

**Comment by GiovanH** [comment]
Should be fixed in 4efd1a5
