### ISSUE TITLE
right arrow key disabled when on laptop at 175% zoom

### ISSUE THREAD

**Issue by Frocto** [GiovanH/unofficial-homestuck-collection#453]
**Describe the bug**
This is a very confusing bug, I'm not sure about the logic behind it at all. Basically I've been reading the collection on my laptop which I run at 200% regular resolution (2560 x 1600). Recently I switched it to 175% zoom so I could see more of the screen and now when I press the 'maximize' button in the top right of the Homestuck Collection I lose the ability to use the right-arrow key to go to the next page.

I can still click the button normally to advance but it's just weird. If I have it in a window that doesn't cover the whole screen the right arrow key works normally. Just interesting I guess?

**To Reproduce**
See above

**Expected behavior**
I press the right arrow key and go to the next page 

**Screenshots**

**Desktop (please complete the following information):**
 - Program version = 2.0.5 win
 - Asset Pack Version = V2
 - OS: [Windows/Mac/Linux version X.XX] = Windows 10

**Comment by Thedude3445** [comment]
I have run into this exact same issue, but without any zoom involved.

**Describe the bug**:

On my main 1440p monitor, the collection works fine at all times. On my secondary 1080p monitor, if the window isn't maximized, it works fine. If UHC is maximized on the 1080p monitor, the right arrow key is disabled for navigation. Scrolling on wide pages, and flashes, still work fine, and all other applications on the PC seem to work fine.

The main 1440p monitor has 125% zoom enabled on Windows, but the 1080p monitor with the issue has no zoom.

Disabling all mods, reloading the app, disabling/reenabling navigation, and factory resetting the app did not change anything.

**Desktop**

- Program: Both 2.0.5 and 2.1.0 did this.
- Asset Pack: V2
- OS: Windows 10
