### ISSUE TITLE
searchable page titles

### ISSUE THREAD

**Issue by emerpie314** [GiovanH/unofficial-homestuck-collection#555]
**Is your feature request related to a problem? Please describe.**
im ticked off at the fact that i cant search for page titles like [S] Descend. or [S] BEGIN INTERMISSION 2.
i tried the log but its so laggy

**Describe the solution you'd like**
i want page titles to be searchable in the homestuck collection

**Comment by GiovanH** [comment]
You're having lag issues with just the adventure log? That's concerning. 

I do agree that page titles should be searchable, I think this is a regression

**Comment by thecnoNSMB** [comment]
I tested this a bit on my (older) version of the UHC, 2.0.7, and I didn't have any lag issues but I was able to reproduce the search problem. It appears that if you type `[S]` into the search bar, no results show.
