### ISSUE TITLE
Links that redirect to browser are instead opened in the Collection

### ISSUE THREAD

**Issue by TheDaringDarson** [GiovanH/unofficial-homestuck-collection#565]
I am currently unable to access any link that would send me to a website or other location on my computer, instead, it attempts to open that link inside the program and returns with a missing page.

1: Find a link that would send you off the program, such as the link to generate a log file or to send you to the list of Third Party Mods.
2: Click on it.
3: It should return with the "That page doesn't exist!" error.

After clicking on the link, it would send you to the appropriate site or location on your computer.

Application version: v2.4.1
Asset pack version: v2
OS: Windows 11 Home 22621.3007

There are some oddities, such as the "The Man-On-Man Suckoff Challenge" and "Cheerfulbear - PLAY ME" links which return a 404 error request on my browser. Some other oddities are the links to Ruffle in the settings and the Ryan North link under Dinosaur Comics, which send me to the homepage.

https://github.com/Bambosh/unofficial-homestuck-collection/assets/98193944/1b97e73a-4090-4d7b-b7b9-6d77ddcfcd4c

**Comment by GiovanH** [comment]
Very strange. Can anyone reproduce this?

**Comment by thecnoNSMB** [comment]
I'm on 2.0.7 on Linux and I can't reproduce this.

**Comment by allusion-codes** [comment]
This issue is occurring for me as well. I'm able to reproduce it in  the following environment:
Application version: v2.5.1
Asset pack version: v2
OS: Windows 11 Home 22631.3737

**Comment by GiovanH** [comment]
Note to self: Doesn't happen with the development version, try with the full installation.

**Comment by gaboscharff99** [comment]
I'm having the same issue with the Flatpak release on Linux Mint 21.3. I updated the Collection to 2.5.2 earlier today, and it's still happening.

**Comment by TheDaringDarson** [comment]
Just got the newest version and it is fixed, thanks! By the way, big fan of your Homescryption mod!
