### ISSUE TITLE
Is the Unofficial Collection compatible with Windows XP?

### ISSUE THREAD

**Issue by tinytumbleweed19** [GiovanH/unofficial-homestuck-collection#566]
For the past day or so, I've been trying to open the Unofficial Collection, but to no avail. I've tried countless things, and it seems I'm at the end of my rope. However, it took this long for the feeble clod that I am to realize that the Unofficial Collection may not even be compatible with a 23-year-old OS. Thus, is the 32-bit version of this program compatible with Windows XP? And—if it is compatible—how do I overcome the following error: "The procedure entry point could not be located in the dynamic link library kernel32.dll."

Thanks in advance.

**Comment by illusoryMechanist** [comment]
You could install [MyPal](https://www.mypal-browser.org/) and try to run the online version of the collection  [(https://homestuck.giovanh.com/#/)](https://homestuck.giovanh.com/#/) instead perhaps? It seems to be an up-to-date browser, so it should be safe-ish to use online if you just go there.

**Comment by GiovanH** [comment]
I have to imagine that many things would go wrong if you tried to use this on Windows XP. It certainly isn't tested or supported.
