### ISSUE TITLE
Minor text formatting issue on page 2923

### ISSUE THREAD

**Issue by LucidusAtra** [GiovanH/unofficial-homestuck-collection#580]
**Description**
With "Spacing between chat paragraphs" checked in the settings, there is a missing space between the word "called" and the word "The" in the 3rd to last message of the Pesterlog on page 2923.

**To Reproduce**
1. Go to settings and enable "Spacing between chat paragraphs"
2. Go to page 2923 and open the Pesterlog.
3. Scroll to the bottom
4. See the missing space in the 3rd message from the bottom.

**Screenshots**

![Bugshot 1](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/d07c0d45-62ec-466a-8748-281e725e45ac)

![bugshot 2](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/68944962-046c-4e74-82bc-947483be7188)

**Desktop (please complete the following information):**
 - Application v2.4.3
 - Asset Pack V2
 - OS: Window 11

(By the way, if these minor formatting errors I'm finding aren't helpful to report, I can stop. But you've fixed the last few, so I'm just gonna assume you want to see them when I find them)

**Comment by LucidusAtra** [comment]
I've found another minor formatting issue on page 2253. Notice the word Lord in the name Lord English is split between two lines. This is probably because of the use of the color-changing pool ball symbol in place of the letter o. This one persists even when "Spacing between chat paragraphs" is switched off, as it's not written in a Pesterlog.

![Minor formatting issue](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/dcc40329-a221-4da6-83c8-d5bcb0462b36)

If there are other pages in which Lord English is spelled with the pool ball symbol in place of the o, this issue might occur on those pages too, but I don't know which pages those would be off the top of my head (I know some pages, like 1155, spell the name normally)

**Comment by GiovanH** [comment]
This one is a stumper; the Lord English text is split up into separate span elements in the source, so CSS doesn't know the img isn't its own element. Looking into patching the text...
