### ISSUE TITLE
Cannot find Module Node:util

### ISSUE THREAD

**Issue by Discord270** [GiovanH/unofficial-homestuck-collection#593]
![image](https://github.com/GiovanH/unofficial-homestuck-collection/assets/173439345/fbfca4e9-f79d-4f1f-ac7c-826fda9d40ac)

**To Reproduce**
1. Use Node.js to install sharp module.
2. Click on application
3. see error

**Expected behavior**
I expected to click the app after finishing the sharp module fix and have it launch as intended

**Desktop
 - Program version 2.0.7
 - Asset Pack Version V2
 - OS Windows 10

What do i even do I am lost when it comes to this stuff

**Comment by GiovanH** [comment]
This should be fixed in the latest version.
