### ISSUE TITLE
Links to website (ie YouTube) not working after the update

### ISSUE THREAD

**Issue by Meufob** [GiovanH/unofficial-homestuck-collection#601]
Clicking on any link that would bring to a website outside the app makes it search inside of it instead.

**Comment by school-dave** [comment]
this and also trying to open the "**Cheerfulbear - PLAY ME**" and "**The origin story.**" of Sweet Bro & Hella Jeff (and maybe other similar links) fails to open correctly in an external browser (it 404s) since the update, at least for me

**Comment by kittenchilly** [comment]
This didn't fix external links it seems. If you try to go to hsmusic.wiki or homestuck.bandcamp.com from the music page it just leads back to the main page and doesn't open anything.

**Comment by GiovanH** [comment]
External links working in the webapp. I also can't reproduce this in 2.5.2 of the app; can someone please confirm that 2.5.2 still has this issue?

**Comment by Meufob** [comment]
Can confirm external links still don't work in 2.5.2.

**Comment by kittenchilly** [comment]
> Can confirm external links still don't work in 2.5.2.

Update to 2.5.4, they should work now
