### ISSUE TITLE
Problem Sleuth Title Screen leads to nothing

### ISSUE THREAD

**Issue by kittenchilly** [GiovanH/unofficial-homestuck-collection#603]
When you click Press Start, it just fades to white and nothing happens. I believe it should redirect you to page 1.

**Comment by kittenchilly** [comment]
It seems to be because the PS_titlescreen.swf in the asset pack was modified, for some reason. If you replace it with the unaltered one from the website http://www.mspaintadventures.com/extras/PS_titlescreen/PS_titlescreen.swf it works fine and redirects without issue

**Comment by GiovanH** [comment]
I am fixing an error in the way the flash player handles link navigation. Thank you!

**Comment by kittenchilly** [comment]
Its fixed for me.
