### ISSUE TITLE
Looking for text files and translation for thesis project

### ISSUE THREAD

**Issue by CoordinatedLobsters** [GiovanH/unofficial-homestuck-collection#617]
Apologies if I'm out of line posting an issue with this topic. I rarely use github, and when I do I spend half my time trying to find the place to download a zip from.
I'm a university student currently doing a master's on translation studies. For my master's thesis next semester, I'm looking to make an annotated translation of (small parts of) Homestuck, and explaining the difficulties that come with trying to bring these varying typing quirks, neologisms and punny foreshadowings into another language (Dutch, in my case). I was hoping this community of devoted Homestuck archivers could help me in my endeavours.
The translation software that I've been taught to use is very useful for translating texts sentence my sentence. It needs a word, pdf, txt or any type of readable file in order to work properly, and considering I'm able to read the full text in the Unofficial Homestuck Collection that I've downloaded onto my computer, I was thinking those files should already be present. I'm having trouble finding them though, and even the Asset Pack download page says it won't do you much aside from being able to view the images.
My first question is, then, is there any place I can find files that have the pure text of Homestuck, preferably page by page? Even if it's not through the Unofficial Homestuck Collection, I'd be much faster for me than going page by page and copy pasting the texts I want to have in a file.
My second question revolves around existing translations. Homestuck.net has a page featuring a long list of translations from Homestuck into various other languages. Have these been modded into the Unofficial Homestuck Collection, and if so, where can I find it?

Again, sorry if this isn't supposed to go into the Issues tab of github, but I couldn't find a better place to ask my questions, especially since they pertain to the Unofficial Homestuck Collection specifically. Even if this isn't supposed to go here, I'd appreciate it if I could be given an answer, or even pointed into the right direction, rather than my Issue being deleted. Thank you in advance.

**Comment by GiovanH** [comment]
The source text for the comic pages can be found in json format within the asset pack at `archive/data/mspa.json`. For any given mspa page number `/mspa/######`, the page text is in the json file under that ID in the "content" field.

The only full translations ported to the UHC I'm aware of are the two on the Third Party Mods page here: https://github.com/GiovanH/unofficial-homestuck-collection/wiki/Third-Party-Mods

If there's anything else I can help with, you can contact me on the [discord server](https://discord.gg/43QHASFC2X) or any of my social media accounts (https://blog.giovanh.com/card.html), I'm interested in the kind of work you're describing and I'd be happy to help if I can.
